# pub keys
keys:
- &users:
    - &pcasaretto age1nf20cvk2lplmurtyxhd9k47rfhmk95kg9522yspnae0zz45d9e0s6jkrk6
- &hosts: # nix-shell -p ssh-to-age --run 'cat /etc/ssh/ssh_host_ed25519_key.pub | ssh-to-age'
    - &nixos age10sw2ucjh9u336ak6l8ggar3rwrk9aj430dgvyuhgyduuqtsjzdcs27wwsc

creation_rules:
    #path should be relative to location of this file (.sops.yaml)
  - path_regex: hosts/common/secrets.yaml$
    key_groups:
    - age:
      - *pcasaretto
      - *nixos
